## End point(s) relative URLs
encryptionPath=v1/identity/encrypt?isInternal=false
internalEncryptionPath=v1/identity/encrypt?isInternal=true
encodePath=v1/identity/encode
decodePath=v1/identity/decode
decryptPath=/idauthentication/v1/internal/decrypt
encodeFilePath=v1/identity/encodeFile
decodeFilePath=v1/identity/decodeFile/?fileName=cbeff
validateSignaturePath=v1/identity/validateSign?signature=$signature$
splitEncryptedData=v1/identity/splitEncryptedData
masterSchemaURL=/v1/masterdata/idschema/latest
preregLoginConfigUrl=/preregistration/v1/login/config
appointmentavailabilityurl=/preregistration/v1/appointment/availability/

## 
regcentretobookappointment=10003

## Check are we using these properties. If not remove them
demoAppVersion=1.2.1-java21-SNAPSHOT

## As these will be based on regEx, move these out from proprties file
passwordForAddIdentity=12341234_Aa
passwordToReset=12341234_AaB