DeleteLostUinApplication:
   Prereg_DeleteLostUinApplication_All_Valid_Smoke_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      uniqueIdentifier: TC_prereg_DeleteLostUinApplication_01
      description: Delete the lost UIN application with valid data
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplicationResult
      input: '{
  "applicationId": "$ID:CreatePrereg_Valid_Smoke_sid_preRegistrationId$"
}'
      output: '{
       "deletedBy": "$IGNORE$"
}'
   Prereg_DeleteLostUinApplication_after_its_deletion:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      uniqueIdentifier: TC_prereg_DeleteLostUinApplication_02
      description: Delete the lost UIN application after it has been removed
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
  "applicationId": "$ID:CreatePrereg_Valid_Smoke_sid_preRegistrationId$"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005"
    }
  ]
}'
   Prereg_DeleteLostUinApplication_multiple_application_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      uniqueIdentifier: TC_prereg_DeleteLostUinApplication_03
      description: Delete the lost UIN application with multiple preregistration IDs for the application
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplicationResult
      input: '{
  "applicationId": "$ID:CreatePrereg_All_Valid_Smoke_UpdateDocRefID_sid_preRegistrationId$"
}'
      output: '{
       "deletedBy": "$IGNORE$"
}'
   Prereg_DeleteLostUinApplication_inValid_preRegistrationId_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      uniqueIdentifier: TC_prereg_DeleteLostUinApplication_04
      description: Delete the lost UIN application with an invalid preregistration ID
      role: batch
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
  "applicationId": "nhhh654443@@ffffv"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005"
    }
  ]
}'
   Prereg_DeleteLostUinApplication_random_number_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      uniqueIdentifier: TC_prereg_DeleteLostUinApplication_05
      description: Delete the lost UIN application with a random number preregistration ID
      role: batch
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
  "applicationId": "12736445738389"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005"
    }
  ]
}'